site:
  title: "MGN Tech - Timeline"
  description: "Bem-vindo a timeline MGN Tech"
personal: 
  name: "Marcelino Neto"
  avatar: "https://github.com/MarcelinoGNeto.png"
  socialNetworks:
    linkedin: "https://www.linkedin.com/in/marcelino-neto"
    github: "https://github.com/MarcelinoGNeto"
    instagram: "https://www.instagram.com/mgn_tech"
    youtube: "https://www.youtube.com/@mgntech"
    twitter: "https://twitter.com/NetoMG3"
